web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - .:/app
    - ./site.conf:/etc/nginx/conf.d/site.conf
  links:
    - php
php:
  image: php:7-fpm
  ports:
    - "9000:9000"
  volumes:
    - .:/app
composer:
  image: composer/composer:php7
  command: install
  volumes:
  - .:/app